[package]
name = "biner"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.86"
publish = false

[dependencies]
linkme = { version = "0.3.32" }
petgraph = { version = "0.8.1", default-features = false, features = ["graphmap"] }
thiserror = "2.0.12"

